import firebase from 'config/fbConfig';

export const auth = firebase.auth();

// AUTH ACTION TYPES
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILIURE = 'LOGIN_FAILIURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_DEFAULT = 'REGISTER_DEFAULT';
export const REGISTER_FAILIURE = 'REGISTER_FAILIURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILIURE = 'LOGOUT_FAILIURE';
// AUTH ACTION END

// BLOG ACTION TYPES START
export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILIURE = 'ADD_ITEM_FAILIURE';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILIURE = 'FETCH_FAILIURE';

export const FETCH_BLOG_REQUEST = 'FETCH_BLOG_REQUEST';
export const FETCH_BLOG_SUCCESS = 'FETCH_BLOG_SUCCESS';
export const FETCH_BLOG_FAILIURE = 'FETCH_BLOG_FAILIURE';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILIURE = 'ADD_COMMENT_FAILIURE';

export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILIURE = 'FETCH_COMMENTS_FAILIURE';

// BLOG ACTION TYPES END
