export default {
  color: {
    primaryColorDark: '#303F9F',
    primaryColor: '#3F51B5',
    primaryColorLight: '#C5CAE9',
    primaryColorText: '#FFFFFF',
    accentColor: '#448AFF',
    primaryTextColor: '#212121',
    secondaryTextColor: '#757575',
    dividerColor: '#BDBDBD',
    twitter: '#1A91DA',
    facebook: '#0676E8',
    github: '#afaaf0',
    linkedin: '#0077B5',
  },
  fontSize: {
    xs: '0.8rem',
    s: '1.2rem',
    m: '1.6rem',
    l: '2rem',
    xl: '2.5rem',
    heading: '3rem',
    headingBig: '4.5rem',
  },
  fontWeight: {
    light: 300,
    regular: 500,
    bold: 700,
  },
};
